//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Get_DellWarranty.DellAssetService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Asset", Namespace="http://support.dell.com/WebServices/")]
    [System.SerializableAttribute()]
    public partial class Asset : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Get_DellWarranty.DellAssetService.AssetHeaderData AssetHeaderDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Get_DellWarranty.DellAssetService.EntitlementData[] EntitlementsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Get_DellWarranty.DellAssetService.Asset[] DupilcateAssetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Get_DellWarranty.DellAssetService.AssetHeaderData AssetHeaderData {
            get {
                return this.AssetHeaderDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetHeaderDataField, value) != true)) {
                    this.AssetHeaderDataField = value;
                    this.RaisePropertyChanged("AssetHeaderData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Get_DellWarranty.DellAssetService.EntitlementData[] Entitlements {
            get {
                return this.EntitlementsField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitlementsField, value) != true)) {
                    this.EntitlementsField = value;
                    this.RaisePropertyChanged("Entitlements");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Get_DellWarranty.DellAssetService.Asset[] DupilcateAssets {
            get {
                return this.DupilcateAssetsField;
            }
            set {
                if ((object.ReferenceEquals(this.DupilcateAssetsField, value) != true)) {
                    this.DupilcateAssetsField = value;
                    this.RaisePropertyChanged("DupilcateAssets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UserMessage {
            get {
                return this.UserMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.UserMessageField, value) != true)) {
                    this.UserMessageField = value;
                    this.RaisePropertyChanged("UserMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssetHeaderData", Namespace="http://support.dell.com/WebServices/")]
    [System.SerializableAttribute()]
    public partial class AssetHeaderData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemModelField;
        
        private System.DateTime SystemShipDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceTag {
            get {
                return this.ServiceTagField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceTagField, value) != true)) {
                    this.ServiceTagField = value;
                    this.RaisePropertyChanged("ServiceTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SystemID {
            get {
                return this.SystemIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemIDField, value) != true)) {
                    this.SystemIDField = value;
                    this.RaisePropertyChanged("SystemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Buid {
            get {
                return this.BuidField;
            }
            set {
                if ((object.ReferenceEquals(this.BuidField, value) != true)) {
                    this.BuidField = value;
                    this.RaisePropertyChanged("Buid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SystemType {
            get {
                return this.SystemTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemTypeField, value) != true)) {
                    this.SystemTypeField = value;
                    this.RaisePropertyChanged("SystemType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SystemModel {
            get {
                return this.SystemModelField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemModelField, value) != true)) {
                    this.SystemModelField = value;
                    this.RaisePropertyChanged("SystemModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime SystemShipDate {
            get {
                return this.SystemShipDateField;
            }
            set {
                if ((this.SystemShipDateField.Equals(value) != true)) {
                    this.SystemShipDateField = value;
                    this.RaisePropertyChanged("SystemShipDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntitlementData", Namespace="http://support.dell.com/WebServices/")]
    [System.SerializableAttribute()]
    public partial class EntitlementData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceLevelCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceLevelDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderField;
        
        private System.DateTime StartDateField;
        
        private System.DateTime EndDateField;
        
        private int DaysLeftField;
        
        private Get_DellWarranty.DellAssetService.EntitlementType EntitlementTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceLevelCode {
            get {
                return this.ServiceLevelCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceLevelCodeField, value) != true)) {
                    this.ServiceLevelCodeField = value;
                    this.RaisePropertyChanged("ServiceLevelCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ServiceLevelDescription {
            get {
                return this.ServiceLevelDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceLevelDescriptionField, value) != true)) {
                    this.ServiceLevelDescriptionField = value;
                    this.RaisePropertyChanged("ServiceLevelDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Provider {
            get {
                return this.ProviderField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderField, value) != true)) {
                    this.ProviderField = value;
                    this.RaisePropertyChanged("Provider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int DaysLeft {
            get {
                return this.DaysLeftField;
            }
            set {
                if ((this.DaysLeftField.Equals(value) != true)) {
                    this.DaysLeftField = value;
                    this.RaisePropertyChanged("DaysLeft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public Get_DellWarranty.DellAssetService.EntitlementType EntitlementType {
            get {
                return this.EntitlementTypeField;
            }
            set {
                if ((this.EntitlementTypeField.Equals(value) != true)) {
                    this.EntitlementTypeField = value;
                    this.RaisePropertyChanged("EntitlementType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntitlementType", Namespace="http://support.dell.com/WebServices/")]
    public enum EntitlementType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expired = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Future = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Credited = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://support.dell.com/WebServices/", ConfigurationName="AssetServiceSoap")]
    public interface AssetServiceSoap {
        
        // CODEGEN: Generating message contract since element name applicationName from namespace http://support.dell.com/WebServices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://support.dell.com/WebServices/GetAssetInformation", ReplyAction="*")]
        Get_DellWarranty.DellAssetService.GetAssetInformationResponse GetAssetInformation(Get_DellWarranty.DellAssetService.GetAssetInformationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAssetInformationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAssetInformation", Namespace="http://support.dell.com/WebServices/", Order=0)]
        public Get_DellWarranty.DellAssetService.GetAssetInformationRequestBody Body;
        
        public GetAssetInformationRequest() {
        }
        
        public GetAssetInformationRequest(Get_DellWarranty.DellAssetService.GetAssetInformationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://support.dell.com/WebServices/")]
    public partial class GetAssetInformationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string applicationName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string serviceTags;
        
        public GetAssetInformationRequestBody() {
        }
        
        public GetAssetInformationRequestBody(System.Guid guid, string applicationName, string serviceTags) {
            this.guid = guid;
            this.applicationName = applicationName;
            this.serviceTags = serviceTags;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAssetInformationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAssetInformationResponse", Namespace="http://support.dell.com/WebServices/", Order=0)]
        public Get_DellWarranty.DellAssetService.GetAssetInformationResponseBody Body;
        
        public GetAssetInformationResponse() {
        }
        
        public GetAssetInformationResponse(Get_DellWarranty.DellAssetService.GetAssetInformationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://support.dell.com/WebServices/")]
    public partial class GetAssetInformationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Get_DellWarranty.DellAssetService.Asset[] GetAssetInformationResult;
        
        public GetAssetInformationResponseBody() {
        }
        
        public GetAssetInformationResponseBody(Get_DellWarranty.DellAssetService.Asset[] GetAssetInformationResult) {
            this.GetAssetInformationResult = GetAssetInformationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AssetServiceSoapChannel : Get_DellWarranty.DellAssetService.AssetServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AssetServiceSoapClient : System.ServiceModel.ClientBase<Get_DellWarranty.DellAssetService.AssetServiceSoap>, Get_DellWarranty.DellAssetService.AssetServiceSoap {
        
        public AssetServiceSoapClient() {
        }
        
        public AssetServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AssetServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssetServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssetServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Get_DellWarranty.DellAssetService.GetAssetInformationResponse Get_DellWarranty.DellAssetService.AssetServiceSoap.GetAssetInformation(Get_DellWarranty.DellAssetService.GetAssetInformationRequest request) {
            return base.Channel.GetAssetInformation(request);
        }
        
        public Get_DellWarranty.DellAssetService.Asset[] GetAssetInformation(System.Guid guid, string applicationName, string serviceTags) {
            Get_DellWarranty.DellAssetService.GetAssetInformationRequest inValue = new Get_DellWarranty.DellAssetService.GetAssetInformationRequest();
            inValue.Body = new Get_DellWarranty.DellAssetService.GetAssetInformationRequestBody();
            inValue.Body.guid = guid;
            inValue.Body.applicationName = applicationName;
            inValue.Body.serviceTags = serviceTags;
            Get_DellWarranty.DellAssetService.GetAssetInformationResponse retVal = ((Get_DellWarranty.DellAssetService.AssetServiceSoap)(this)).GetAssetInformation(inValue);
            return retVal.Body.GetAssetInformationResult;
        }
    }
}
